version: '3.9'

services:
  app:
    image: cinema-eng:1.0.0
    container_name: cinema-eng-container
    build: .
    entrypoint: "python manage.py runserver 0.0.0.0:8000"
    volumes: 
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - cinema-ntw
  db:
    image: mysql:8.0.28-oracle
    container_name: cinema-db-container
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      TZ: Asia/Tehran
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - cinema-ntw
  
volumes:
  mysql_data:

networks:
  cinema-ntw:
    driver: bridge