# Generated by Django 4.0.4 on 2022-04-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chair',
            name='availability',
        ),
    ]
