# Generated by Django 4.0.4 on 2022-04-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_myuser_firstname_myuser_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chair',
            name='show',
        ),
    ]
